sudo: false

language: php

php:
  - 5.4
  - 5.5
  - hhvm

install:
  - "./ci/_composer_install.sh"
  - mkdir -p build/logs
  - "./ci/start-ci.sh $ORIENTDB_VERSION"

cache:
  directories:
  - ./ci/environment/orientdb-community-$ORIENTDB_VERSION
  - ./vendor

before_cache:
- ls -la ./ci/environment/
- rm -f ./ci/environment/orientdb-community-$ORIENTDB_VERSION/log/*
- rm -rf ./ci/environment/orientdb-community-$ORIENTDB_VERSION/databases/*

script:
 - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php ./vendor/bin/coveralls -v

env:
  - ORIENTDB_VERSION=2.1.5
  - ORIENTDB_VERSION=2.1.4
  - ORIENTDB_VERSION=2.1.3
  - ORIENTDB_VERSION=2.1.2
  - ORIENTDB_VERSION=2.1.1
  - ORIENTDB_VERSION=2.1.0
  - ORIENTDB_VERSION=2.0.13
  - ORIENTDB_VERSION=1.7.10