language: php

php:
  - 5.4
#  - 5.5
#  - hhvm

before_script:
  - ./ci/start-ci.sh $ORIENTDB_VERSION
  - composer install --prefer-source

script: ./vendor/bin/phpunit

env:
#  - ORIENTDB_VERSION=2.0-rc1
#  - ORIENTDB_VERSION=1.7.8
  - ORIENTDB_VERSION=1.7.7
#  - ORIENTDB_VERSION=1.7.4

matrix:
  allow_failures:
#    - ORIENTDB_VERSION=2.0-rc1
